//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MaintenanceOrdersInBound
{


    // ####################################################################################################################


    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.xmlsoap.org/soap/envelope/", IsNullable = false)]
    public partial class Envelope
    {

        private EnvelopeBody bodyField;

        /// <remarks/>


        /// <remarks/>
        public EnvelopeBody Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
    public partial class EnvelopeBody
    {

        //private CreateMaintenanceOrdersResponse createMaintenanceOrdersResponseField;

        /// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://iec.ch/TC57/2014/MaintenanceOrdersMessage")]
        //public CreateMaintenanceOrdersResponse CreateMaintenanceOrdersResponse
        //{
        //    get
        //    {
        //        return this.createMaintenanceOrdersResponseField;
        //    }
        //    set
        //    {
        //        this.createMaintenanceOrdersResponseField = value;
        //    }
        //}


        //// Methods earlier in WorkOrder
        private MaintenanceOrdersResponseMessageType maintenanceOrdersEventMessageTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://iec.ch/TC57/2014/MaintenanceOrdersMessage")]
        public MaintenanceOrdersResponseMessageType CreateMaintenanceOrdersResponse
        {
            get
            {
                return this.maintenanceOrdersEventMessageTypeField;
            }
            set
            {
                this.maintenanceOrdersEventMessageTypeField = value;
            }
        }


        //private CreateMaintenanceOrdersResponse createMaintenanceOrdersResponseField;

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://iec.ch/TC57/2014/MaintenanceOrdersMessage")]
        //public CreateMaintenanceOrdersResponse CreateMaintenanceOrdersResponse
        //{
        //    get
        //    {
        //        return this.createMaintenanceOrdersResponseField;
        //    }
        //    set
        //    {
        //        this.createMaintenanceOrdersResponseField = value;
        //    }
        //}

        private MaintenanceOrdersResponseMessageType iFSMaintenanceOrdersResponseMessageTypeField;


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://iec.ch/TC57/2014/MaintenanceOrdersMessage")]
        public MaintenanceOrdersResponseMessageType IFSMaintenanceOrdersResponse
        {
            get
            {
                return this.iFSMaintenanceOrdersResponseMessageTypeField;
            }
            set
            {
                this.iFSMaintenanceOrdersResponseMessageTypeField = value;
            }
        }


        private MaintenanceOrdersEventMessageType changedMaintenanceOrdersField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://iec.ch/TC57/2014/MaintenanceOrdersMessage")]
        public MaintenanceOrdersEventMessageType ChangedMaintenanceOrders
        {
            get
            {
                return this.changedMaintenanceOrdersField;
            }
            set
            {
                this.changedMaintenanceOrdersField = value;
            }
        }

    }


    // ####################################################################################################################








}
